name: Testing stuff

on:
  push:
    branches:
      - main
jobs:
  a_test_job:
    env:
      COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        if: ${{!contains(join(env.COMMIT_MESSAGES, ''), '#skip')}}
        run: echo "$COMMIT_MESSAGES"
      - name: commit url
        env:
          COMMIT_URL: ${{ github.event.head_commit.url }}
        run: echo "$COMMIT_URL"
